# Assignment 2B

In [ ]:
import numpy as np

In [16]:
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [12]:
wh = np.around(np.random.random((4,3)),decimals=2)
wh

array([[0.24, 0.96, 0.3 ],
       [0.84, 0.11, 0.68],
       [0.6 , 0.06, 0.93],
       [0.82, 0.56, 0.17]])

In [13]:
bh = np.around(np.random.random((1,3)),decimals=2)
bh

array([[0.14, 0.13, 0.08]])

In [18]:
hidden_layer_input = np.dot(X,wh) + bh
hidden_layer_input

array([[0.98, 1.15, 1.31],
       [1.8 , 1.71, 1.48],
       [1.8 , 0.8 , 0.93]])

In [22]:
def sigmoid(x):
    return 1 / (1 + np.e ** -x)
hiddenlayer_activations=np.around(sigmoid(hidden_layer_input),2)

In [23]:
hiddenlayer_activations

array([[0.73, 0.76, 0.79],
       [0.86, 0.85, 0.81],
       [0.86, 0.69, 0.72]])

In [24]:
wout = np.around(np.random.random((3,1)),decimals=2)
wout

array([[0.74],
       [0.95],
       [0.09]])

In [25]:
bout = np.around(np.random.random((1,1)),decimals=2)
bout

array([[0.77]])

In [26]:
output_layer_input = np.dot(hiddenlayer_activations,wout)+bout
output_layer_input

array([[2.1033],
       [2.2868],
       [2.1267]])

In [29]:
output=np.around(sigmoid(output_layer_input),2)

In [30]:
output

array([[0.89],
       [0.91],
       [0.89]])

In [31]:
y = np.array([[1],[1],[0]])
y

array([[1],
       [1],
       [0]])

In [32]:
E = y-output
E

array([[ 0.11],
       [ 0.09],
       [-0.89]])

In [40]:
def derivatives_sigmoid(x):
    return (sigmoid(x)*(1-sigmoid(x)))
Slope_output_layer= np.around(derivatives_sigmoid(output),2)
Slope_hidden_layer= np.around(derivatives_sigmoid(hiddenlayer_activations),2)

In [41]:
Slope_output_layer

array([[0.21],
       [0.2 ],
       [0.21]])

In [42]:
Slope_hidden_layer

array([[0.22, 0.22, 0.21],
       [0.21, 0.21, 0.21],
       [0.21, 0.22, 0.22]])

In [44]:
learning_rate=0.1
d_output = E*Slope_output_layer*learning_rate

In [45]:
d_output

array([[ 0.00231],
       [ 0.0018 ],
       [-0.01869]])

In [46]:
Error_at_hidden_layer = np.dot(d_output, np.transpose(wout))
Error_at_hidden_layer

array([[ 0.0017094,  0.0021945,  0.0002079],
       [ 0.001332 ,  0.00171  ,  0.000162 ],
       [-0.0138306, -0.0177555, -0.0016821]])

In [52]:
d_hiddenlayer = Error_at_hidden_layer * Slope_hidden_layer
d_hiddenlayer

array([[ 3.760680e-04,  4.827900e-04,  4.365900e-05],
       [ 2.797200e-04,  3.591000e-04,  3.402000e-05],
       [-2.904426e-03, -3.906210e-03, -3.700620e-04]])

In [53]:
wout = wout + np.dot(np.transpose(hiddenlayer_activations), d_output) * learning_rate
wout

array([[0.73871609],
       [0.94903895],
       [0.08898261]])

In [54]:
wh = wh+ np.dot(np.transpose(X),d_hiddenlayer) * learning_rate
wh

array([[0.24006558, 0.96008419, 0.30000777],
       [0.83970956, 0.10960938, 0.67996299],
       [0.60006558, 0.06008419, 0.93000777],
       [0.81973753, 0.55964529, 0.1699664 ]])

In [55]:
bh = bh + np.sum(d_hiddenlayer, axis=0) * learning_rate
bh

array([[0.13977514, 0.12969357, 0.07997076]])

In [56]:
bout = bout + np.sum(d_output, axis=0)*learning_rate
bout

array([[0.768542]])